language: php
php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - nightly

matrix:
    allow_failures:
        - php: nightly
    fast_finish: true

env:
    matrix:
        - DEPENDENCIES="high"
        - DEPENDENCIES="low"
    global:
        - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-ansi --no-progress --no-suggest"

cache:
    directories:
        - $HOME/.composer/cache/files

before_install:
    - composer validate

install:
    - if [[ "$DEPENDENCIES" = 'high' ]]; then travis_retry composer update $DEFAULT_COMPOSER_FLAGS; fi
    - if [[ "$DEPENDENCIES" = 'low' ]]; then travis_retry composer update $DEFAULT_COMPOSER_FLAGS --prefer-lowest; fi

script:
    - vendor/bin/phpunit --configuration phpunit.xml.dist

notifications:
    email:
        on_failure: change
